--- #YAML:1.0
name:               Perl-Unsafe-Signals
version:            0.03
abstract:           Allow unsafe handling of signals in selected blocks
author:
    - Rafael Garcia-Suarez <rgs@consttype.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    repository:
        type:  git
        url:   https://github.com/rgs/Perl-Unsafe-Signals.git
        web:   https://github.com/rgs/Perl-Unsafe-Signals
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  2
